insert into `categories` (`category`, `id`) values ('Books', 1);
insert into `categories` (`category`, `id`) values ('Business & Industrial', 2);
insert into `categories` (`category`, `id`) values ('Clothing, Shoes & Accessories', 3);
insert into `categories` (`category`, `id`) values ('Collectibles', 4);
insert into `categories` (`category`, `id`) values ('Consumer Electronics', 5);
insert into `categories` (`category`, `id`) values ('Crafts', 6);
insert into `categories` (`category`, `id`) values ('Dolls & Bears', 7);
insert into `categories` (`category`, `id`) values ('Home & Garden', 8);
insert into `categories` (`category`, `id`) values ('Motors', 9);
insert into `categories` (`category`, `id`) values ('Pet Supplies', 10);
insert into `categories` (`category`, `id`) values ('Sporting Goods', 11);
insert into `categories` (`category`, `id`) values ('Sports Mem, Cards & Fan Shop', 12);
insert into `categories` (`category`, `id`) values ('Toys & Hobbies', 13);
insert into `categories` (`category`, `id`) values ('Antiques', 14);
insert into `categories` (`category`, `id`) values ('Computers/Tablets & Networking', 15);
